#!/usr/bin/node

const readlineSync = require('readline-sync');

const frase = readlineSync.question("Digite uma frase: ");

console.log(frase.toUpperCase().replaceAll("A", "I"), frase.length); /* SUBI NUM ÔNIBUS EM MARRICIS 28 */


